name: For Comment Feedback Collection
description: >
  Submit feedback for IG profiles during the For Comment phase. 
title: "For Comment: Feedback for [Profile Name]" 
assignees: 
  - JamedFV
labels: []
projects: []

body: 
  - type: input
    id: link_to_profile
    attributes: 
      label: Link to Profile
      description: "Please provide the link to the profile being reviewed." 
      placeholder: "Enter the profile URL" 
    validations: 
      required: true
  - type: textarea
    id: feedback
    attributes: 
      label: Feedback Submission
      description: "Please describe your feedback in detail, including concerns, suggestions, or areas for improvement." 
      placeholder: "Enter your feedback here"
    validations:
      required: true
  - type: dropdown
    id: implementation_blocking
    attributes: 
      label: "Is this feedback implementation-blocking?" 
      description: "Select whether this issue blocks implementation."
      options:
        - Yes, this issue will block implementation.
        - No, this issue does not block implementation.
      validations: 
        required: true
