name: STU Ballot Participant Module
description: >
  Capture votes and comments for the STU Ballot for the Participant Module.
title: "STU Ballot - Participant Module"
labels: 
  - STU Ballot
  - Participant Module

body: 
  - type: markdown
    attributes: 
      value: |
        ### Purpose of the STU Ballot
        This issue is for the **Participant Module STU Ballot**. The goal of this ballot is to determine whether this module is ready for trial use across all platforms' implementation. Feedback gathered during the trial period will inform further refinements before the module progress to the Normative Ballot. 
        
  - type: markdown
    attributes: 
      value: |
        ### Voting Instructions
        - Each platform should cast its vote for the Participant Module. 
        - Each platform is allowed **one vote** (submitted by the assigned POC) that will inform the outcome of the ballot.
          - **Other votes are permitted**, but will not be considered in the pass/fail determination of the ballot. 
        - Please follow the format and instructions provided under the "Voting Template" to record your vote. 

        ### Voting Template
        Copy and paste the following template into a comment to case your vote:
        '''markdown
        **Platform Name**: [Your platform name here]
        **Vote**: [Affirmative | Negative with Comments]
        **Comments**: 
        - [Your comments here. If voting "Negative with Comments," include specific concerns or suggestions.]
        '''

  - type: checkboxes
    id: platform_completion
    attributes: 
      label: Platforms Voting Checklist
      description: "Please check off your platform once you have submitted your vote in the comments."
      options:
        - label: AnVIL
        - label: Kids First DRC
        - label: ImmPort
        - label: Bio Data Catalyst (BDC) 
        - label: Cancer Research Data Commons (CRDC)
        - label: dbGaP 

  - type: markdown 
    attributes: 
      value: | 
        ### Voting Period
        - The voting period if open from **November 26, 2024** to **December 31, 2024**.
